#!/usr/bin/env python3
"""
IR-based RTL Backtracking Engine

Input:
  - <design>_ir.json   (generated by ir_builder.py)

Output:
  - <design>_backtracking.csv
  - <design>_backtracking.json
"""

import json
import csv
import re
from collections import defaultdict
from pathlib import Path

from alias_engine import AliasEngine

# ================================================================
# Configuration
# ================================================================

MAX_DEPTH = 3

# ================================================================
# IR LOAD
# ================================================================

def load_ir_json(path):
    with open(path) as f:
        return json.load(f)

# ================================================================
# IR -> DRIVERS
# ================================================================

def build_drivers_from_ir(ir):
    """
    Convert IR records into canonical drivers dict.

    drivers[lhs] = [
        {
            rhs,
            condition,
            construct,
            assign_type,
            sensitivity,
            file,
            always_block_id  (if available from IR)
        }
    ]
    """
    drivers = defaultdict(list)

    for rec in ir:
        lhs = rec["signal"]

        assign_type = (
            "nonblocking"
            if rec["timing"] == "next_cycle"
            else "blocking"
        )

        sensitivity = None
        if rec["process"] in ("always", "always_ff"):
            if rec["clock"]:
                sensitivity = f"{rec['clock_edge']} {rec['clock']}"
                if rec["reset"]:
                    sensitivity += f" or {rec['reset_edge']} {rec['reset']}"

        proc = rec["process"]   # initial / always / always_ff / always_comb / assign

        drivers[lhs].append({
            "rhs": rec["rhs"],
            "condition": rec["guard"],
            "construct": proc,
            "proc_type": (
                "INITIAL" if proc == "initial"
                else "ALWAYS" if proc.startswith("always")
                else "CONT"
            ),
            "assign_type": assign_type,
            "sensitivity": sensitivity,
            "file": rec.get("source", ""),
            "always_block_id": rec.get("always_block_id", None)
        })


    return drivers

# ================================================================
# ALIAS DETECTION
# ================================================================

def is_pure_alias_signal(sig, drivers):
    """
    True if sig is ONLY driven by: assign sig = other_signal;
    """
    if sig not in drivers:
        return False

    drvs = drivers[sig]
    if len(drvs) != 1:
        return False

    d = drvs[0]

    if d.get("construct") != "assign":
        return False

    rhs = d.get("rhs", "").strip()
    return bool(re.fullmatch(r"[a-zA-Z_]\w*", rhs))

def build_aliases(drivers):
    alias_engine = AliasEngine()

    # 1. Forward aliases (existing behavior)
    alias_engine.detect_pure_assign_aliases(drivers)

    # 2. Reverse aliases (NEW, controlled)
    for lhs in drivers:
        if is_pure_alias_signal(lhs, drivers):
            rhs = drivers[lhs][0]["rhs"].strip()
            alias_engine.add_alias(rhs, lhs)

    return alias_engine

def bidirectional_alias_chain(alias_engine, sig):
    """
    Show both upstream and downstream aliases:
    A <- B <- sig -> C -> D
    
    Handles cycles gracefully by tracking visited nodes.
    """
    left = []
    cur = sig
    visited_upstream = set([sig])  # Track visited nodes to prevent infinite loops

    # Walk upstream (reverse aliases) - WITH CYCLE DETECTION
    while True:
        parents = list(alias_engine.aliases_to.get(cur, []))
        if not parents:
            break
        
        # Take first parent
        nxt = parents[0]
        
        # Cycle detection: stop if we've seen this node before
        if nxt in visited_upstream:
            break
        
        visited_upstream.add(nxt)
        left.append(nxt)
        cur = nxt

    left = left[::-1]

    # Walk downstream (forward aliases) - ALREADY HAS CYCLE DETECTION
    right = []
    cur = sig
    visited_downstream = set([sig])  # Separate visited set for downstream

    while cur in alias_engine.alias_of:
        nxt = alias_engine.alias_of[cur]
        
        # Cycle detection: stop if we've seen this node before
        if nxt in visited_downstream:
            break
        
        visited_downstream.add(nxt)
        right.append(nxt)
        cur = nxt

    return left + [sig] + right

# ================================================================
# EXPRESSION HELPERS
# ================================================================

def extract_signals(expr):
    if not expr:
        return []
    return re.findall(r'\b[a-zA-Z_]\w*\b', expr)

def extract_condition_signals(cond):
    if not cond:
        return []
    return extract_signals(cond)

def extract_mux(rhs):
    """
    Detect ternary mux:
        a ? b : c
    """
    if not rhs:
        return None
    m = re.match(r'(.+)\?(.+):(.+)', rhs)
    if not m:
        return None

    cond, t, f = m.groups()
    return [
        {"rhs": t.strip(), "condition": cond.strip()},
        {"rhs": f.strip(), "condition": f"!({cond.strip()})"},
    ]

# ================================================================
# HELPER: Check if two drivers are from the same always block
# ================================================================

def same_always_block(drv1, drv2):
    """
    Check if two drivers are from the same always block.
    
    Priority:
    1. If always_block_id exists in both, compare them
    2. Otherwise, compare source file location (SourceRange object string)
    3. Fall back to sensitivity + construct comparison
    """
    # Method 1: Use always_block_id if available (most reliable)
    id1 = drv1.get("always_block_id")
    id2 = drv2.get("always_block_id")
    
    if id1 is not None and id2 is not None:
        return id1 == id2
    
    # Method 2: Compare file/source location (SourceRange)
    # Different assignments in same always block may have same or different SourceRange
    # So we also need to check sensitivity
    file1 = str(drv1.get("file", ""))
    file2 = str(drv2.get("file", ""))
    
    # Only trust explicit always_block_id
    id1 = drv1.get("always_block_id")
    id2 = drv2.get("always_block_id")

    if id1 is not None and id2 is not None:
        return id1 == id2

    # If IDs not available, assume DIFFERENT blocks (safer)
    return False


# ================================================================
# ALIAS CHAIN FORMATTING
# ================================================================

def format_alias_chain(alias_chain, max_display=3):
    """
    Format alias chain for display, limiting to max_display aliases.
    
    Examples:
        [A, B, C] -> "A -> B -> C"
        [A, B, C, D, E] -> "A -> ... -> E"  (show first and last)
        [A, B, C, D, E, F, G] -> "A -> ... -> G"
    """
    if len(alias_chain) <= max_display:
        return " -> ".join(alias_chain)
    
    # Show first and last with "..." in between
    first = alias_chain[0]
    last = alias_chain[-1]
    
    return f"{first} -> ... -> {last}"

# ================================================================
# RECURSIVE BACKTRACKING
# ================================================================

def recurse_signal(
    sig,
    drivers,
    alias_engine,
    rows,
    depth=1,
    parent=None,
    visited=None,
):
    if visited is None:
        visited = set()

    if sig in visited or depth > MAX_DEPTH:
        return

    visited.add(sig)

    alias_chain = bidirectional_alias_chain(alias_engine, sig)
    
    # Limit alias chain display to 3 aliases
    alias_str = format_alias_chain(alias_chain, max_display=3)

    # Leaf node
    if sig not in drivers:
        rows.append([
            sig,
            alias_str,
            depth,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",  # always_block_id (empty for leaf nodes)
            parent or ""
        ])
        return

    for idx, drv in enumerate(drivers[sig], start=1):
        rhs = drv["rhs"]
        cond = drv["condition"]

        rows.append([
            sig,
            alias_str,
            depth,
            idx,
            rhs,
            cond or "",
            drv["construct"],
            drv["file"],
            drv.get("sensitivity", ""),
            drv["assign_type"],
            drv.get("always_block_id", ""),  # FIX: Include always_block_id in CSV
            parent or ""
        ])

        # --- recurse condition signals ---
        for cs in extract_condition_signals(cond):
            recurse_signal(
                cs,
                drivers,
                alias_engine,
                rows,
                depth + 1,
                sig,
                visited.copy()
            )

        # --- recurse RHS signals ---
        mux = extract_mux(rhs)
        if mux:
            for br in mux:
                for s in extract_signals(br["rhs"]):
                    recurse_signal(
                        s,
                        drivers,
                        alias_engine,
                        rows,
                        depth + 1,
                        sig,
                        visited.copy()
                    )
        else:
            for s in extract_signals(rhs):
                recurse_signal(
                    s,
                    drivers,
                    alias_engine,
                    rows,
                    depth + 1,
                    sig,
                    visited.copy()
                )
        
        # Check if next driver is from a different always block
        if depth == 1 and idx < len(drivers[sig]):
            next_drv = drivers[sig][idx]  # idx is 1-based, so drivers[sig][idx] is the next driver
            # Add separator only when transitioning to a new always block
            if not same_always_block(drv, next_drv):
                rows.append(["--- NEXT DRIVER ---"] + [""] * 11)  # FIX: Updated to match new column count

# ================================================================
# CSV OUTPUT
# ================================================================

def save_backtracking_csv(drivers, alias_engine, filename):
    rows = []

    for sig in drivers.keys():
        recurse_signal(sig, drivers, alias_engine, rows)
        rows.append([""] * 12)  # FIX: Updated separator row to match new column count

    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "signal",
            "alias_chain",
            "depth",
            "driver_idx",
            "rhs",
            "condition",
            "construct",
            "file",
            "sensitivity",
            "assign_type",
            "always_block_id",  # FIX: Added always_block_id column to header
            "parent"
        ])
        writer.writerows(rows)

# ================================================================
# JSON OUTPUT
# ================================================================

def save_backtracking_json(drivers, alias_engine, filename):
    out = {}

    for sig in drivers:
        out[sig] = {
            "alias_chain": alias_engine.chain(sig),
            "drivers": drivers[sig]
        }

    with open(filename, "w") as f:
        json.dump(out, f, indent=2)

# ================================================================
# MAIN
# ================================================================

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python ir_backtracking.py <ir.json>")
        sys.exit(1)

    ir_json = sys.argv[1]
    base = Path(ir_json).stem

    print(f"[IR] Loading {ir_json}")
    ir = load_ir_json(ir_json)

    print("[IR] Building drivers")
    drivers = build_drivers_from_ir(ir)

    print("[IR] Detecting aliases")
    alias_engine = build_aliases(drivers)

    csv_out = f"{base}_backtracking.csv"
    json_out = f"{base}_backtracking.json"

    print("[OUT] Writing CSV")
    save_backtracking_csv(drivers, alias_engine, csv_out)

    print("[OUT] Writing JSON")
    save_backtracking_json(drivers, alias_engine, json_out)

    print(f"[DONE] Generated:")
    print(f"  - {csv_out}")
    print(f"  - {json_out}")


def run_ir_backtracking(ir_json_path, out_csv, out_json):
    with open(ir_json_path) as f:
        ir = json.load(f)

    drivers = build_drivers_from_ir(ir)

    alias_engine = AliasEngine()
    for lhs, drvs in drivers.items():
        for d in drvs:
            rhs = d["rhs"]
            if re.fullmatch(r'[a-zA-Z_]\w*', rhs):
                alias_engine.add_alias(lhs, rhs)

    save_backtracking_csv(drivers, alias_engine, out_csv)
    save_backtracking_json(drivers, alias_engine, out_json)